file(MAKE_DIRECTORY "${WORK}")
execute_process(COMMAND "${ZLANG}" build "${SOURCE}" -o "${WORK}/program" RESULT_VARIABLE c OUTPUT_VARIABLE co ERROR_VARIABLE ce)
if(NOT c EQUAL 0)
 message(FATAL_ERROR "compile failed: ${co}\n${ce}")
endif()
execute_process(COMMAND "${WORK}/program" RESULT_VARIABLE r OUTPUT_VARIABLE actual ERROR_VARIABLE err)
file(READ "${EXPECTED}" expected)
if(NOT r EQUAL 0 OR NOT actual STREQUAL expected)
 message(FATAL_ERROR "run mismatch rc=${r}\nexpected=[${expected}]\nactual=[${actual}]\nstderr=${err}")
endif()
