#include "zlang/CodeGen.h"
#include <fstream>
#include <iomanip>
#include <sstream>
namespace zlang {std::string CppCodeGenerator::esc(const std::string&s){std::ostringstream o;for(unsigned char c:s){switch(c){case'\\':o<<"\\\\";break;case'"':o<<"\\\"";break;case'\n':o<<"\\n";break;case'\r':o<<"\\r";break;case'\t':o<<"\\t";break;case 0:o<<"\\0";break;default:o<<c;}}return o.str();}std::string CppCodeGenerator::expr(const Expr&e){if(auto*x=dynamic_cast<const LiteralExpr*>(&e)){if(auto v=std::get_if<std::int64_t>(&x->value))return"V(I{"+std::to_string(*v)+"})";if(auto v=std::get_if<double>(&x->value)){std::ostringstream o;o<<std::setprecision(17)<<*v;return"V(D{"+o.str()+"})";}if(auto v=std::get_if<std::string>(&x->value))return"V(S{\""+esc(*v)+"\"})";return std::get<bool>(x->value)?"V(true)":"V(false)";}if(auto*x=dynamic_cast<const NameExpr*>(&e))return"v_"+x->name;if(auto*x=dynamic_cast<const UnaryExpr*>(&e))return"un(\""+x->op+"\","+expr(*x->rhs)+")";if(auto*x=dynamic_cast<const BinaryExpr*>(&e))return"bin(\""+x->op+"\","+expr(*x->lhs)+","+expr(*x->rhs)+")";if(auto*x=dynamic_cast<const CallExpr*>(&e)){std::string r=x->callee=="cpx"?"make_cpx(":"z_"+x->callee+"(";for(size_t i=0;i<x->args.size();++i){if(i)r+=",";r+=expr(*x->args[i]);}return r+")";}return"V{}";}void CppCodeGenerator::stmt(const Stmt&s,int n){std::string in(n,' ');if(auto*x=dynamic_cast<const VarDecl*>(&s))out_+=in+"V v_"+x->name+"="+expr(*x->init)+";\n";else if(auto*x=dynamic_cast<const Assign*>(&s))out_+=in+"v_"+x->name+"="+expr(*x->value)+";\n";else if(auto*x=dynamic_cast<const Print*>(&s)){for(auto&a:x->args)out_+=in+"zprint("+expr(*a)+");\n";}else if(auto*x=dynamic_cast<const Return*>(&s))out_+=in+"return "+(x->value?expr(*x->value):"V{}")+";\n";else if(auto*x=dynamic_cast<const ExprStmt*>(&s))out_+=in+expr(*x->expr)+";\n";else if(auto*x=dynamic_cast<const If*>(&s)){out_+=in+"if(truth("+expr(*x->cond)+")){\n";for(auto&a:x->thenBlock->statements)stmt(*a,n+2);out_+=in+"}";for(auto&b:x->elseIfs){out_+="else if(truth("+expr(*b.first)+")){\n";for(auto&a:b.second->statements)stmt(*a,n+2);out_+=in+"}";}if(x->elseBlock){out_+="else{\n";for(auto&a:x->elseBlock->statements)stmt(*a,n+2);out_+=in+"}";}out_+="\n";}else if(auto*x=dynamic_cast<const While*>(&s)){out_+=in+"while(truth("+expr(*x->cond)+")){\n";for(auto&a:x->body->statements)stmt(*a,n+2);out_+=in+"}\n";}else if(auto*x=dynamic_cast<const For*>(&s)){out_+=in+"for(I _i=0,_n=range_end("+expr(*x->end)+");_i<_n;++_i){V v_"+x->name+"=V(_i);\n";for(auto&a:x->body->statements)stmt(*a,n+2);out_+=in+"}\n";}}
bool CppCodeGenerator::generate(const Program&p,const std::filesystem::path&path){out_=R"CPP(#include <cmath>
#include <complex>
#include <cstdint>
#include <cstdlib>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <variant>
#ifdef _WIN32
#include <windows.h>
#endif
using I=std::int64_t;using D=double;using S=std::string;using C=std::complex<double>;using V=std::variant<std::monostate,I,D,S,bool,C>;
static double num(const V&v){if(auto x=std::get_if<I>(&v))return(double)*x;if(auto x=std::get_if<D>(&v))return*x;throw std::runtime_error("numeric value required");}static bool truth(const V&v){if(auto x=std::get_if<bool>(&v))return*x;throw std::runtime_error("bool required");}static V make_cpx(const V&a,const V&b){return C(num(a),num(b));}static I range_end(const V&v){double d=num(v);if(!std::isfinite(d)||std::floor(d)!=d)throw std::runtime_error("range end must be an integer");return d<=0?0:(I)d;}static V un(const char*o,const V&a){double x=num(a);if(std::string(o)=="+")return a;return std::holds_alternative<I>(a)?V(-std::get<I>(a)):V(-x);}static V bin(const std::string&o,const V&a,const V&b){if(o=="==")return a==b;if(o=="!=")return a!=b;if((o=="+"||o=="-"||o=="*"||o=="/")&&std::holds_alternative<C>(a)&&std::holds_alternative<C>(b)){auto x=std::get<C>(a),y=std::get<C>(b);if(o=="+")return x+y;if(o=="-")return x-y;if(o=="*")return x*y;if(y==C{})throw std::runtime_error("division by zero");return x/y;}if(o=="+"&&std::holds_alternative<S>(a)&&std::holds_alternative<S>(b))return std::get<S>(a)+std::get<S>(b);double x=num(a),y=num(b);if(o=="<")return x<y;if(o=="<=")return x<=y;if(o==">")return x>y;if(o==">=")return x>=y;if(o=="/"&&y==0)throw std::runtime_error("division by zero");if(o=="/")return x/y;bool ints=std::holds_alternative<I>(a)&&std::holds_alternative<I>(b);if(o=="+")return ints?V(std::get<I>(a)+std::get<I>(b)):V(x+y);if(o=="-")return ints?V(std::get<I>(a)-std::get<I>(b)):V(x-y);if(o=="*")return ints?V(std::get<I>(a)*std::get<I>(b)):V(x*y);throw std::runtime_error("invalid operator");}static std::string text(const V&v){if(auto x=std::get_if<I>(&v))return std::to_string(*x);if(auto x=std::get_if<D>(&v)){std::ostringstream o;o<<std::setprecision(15)<<*x;return o.str();}if(auto x=std::get_if<S>(&v))return*x;if(auto x=std::get_if<bool>(&v))return*x?"true":"false";if(auto x=std::get_if<C>(&v)){std::ostringstream o;o<<x->real()<<(x->imag()<0?"":"+")<<x->imag()<<"i";return o.str();}return"";}static void zprint(const V&v){std::cout<<text(v);}
)CPP";for(auto&f:p.functions){out_+="static V z_"+f->name+"(";for(size_t i=0;i<f->params.size();++i){if(i)out_+=",";out_+="V v_"+f->params[i];}out_+=");\n";}for(auto&f:p.functions){out_+="static V z_"+f->name+"(";for(size_t i=0;i<f->params.size();++i){if(i)out_+=",";out_+="V v_"+f->params[i];}out_+="){\n";for(auto&s:f->body->statements)stmt(*s,2);out_+="return V{};\n}\n";}out_+=R"CPP(int main(){
#ifdef _WIN32
SetConsoleOutputCP(CP_UTF8);SetConsoleCP(CP_UTF8);
#endif
try{z_main();return 0;}catch(const std::exception&e){std::cerr<<"runtime error: "<<e.what()<<"\n";return 5;}}
)CPP";std::ofstream f(path,std::ios::binary);f<<out_;return(bool)f;}}
